"""
src/pages/page8_forecast.py
---------------------------
What-if scenario builder: readership decay forecasting.

Reads pre-computed retention rates from data/predictions.json (generated by
scripts/train.py) and lets users explore decay trajectories for any hypothetical
issue-2 opening baseline. No sklearn required at runtime.
"""

import json
import numpy as np
import streamlit as st
import plotly.graph_objects as go
from pathlib import Path
from scipy import stats as scipy_stats

from src.utils.styling import (
    page_header, prose, pull_quote, section_heading, data_note, PLOTLY_LAYOUT
)

PRED_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "predictions.json"

ISSUE_LABELS = {2: "#2", 6: "#6", 12: "#12", 24: "#24", 36: "#36"}
ISSUE_POINTS  = [2, 6, 12, 24, 36]

# Colours for historical volume lines
VOL_COLORS = {
    2: "#555555",   # 1999 greyed out (different era)
    3: "#7799cc",   # 2014 Slott
    4: "#77aadd",   # 2015 Slott
    5: "#6fbf7a",   # 2018 Spencer (best performer)
    6: "#e8b84b",   # 2022 Wells (PRH estimate)
}

SCENARIO_COLOR = "#e23636"
CI_FILL_COLOR  = "rgba(226,54,54,0.12)"


@st.cache_data
def load_predictions():
    if not PRED_PATH.exists():
        return None
    with open(PRED_PATH) as f:
        return json.load(f)


def compute_trajectory(issue2_orders, retention):
    """
    Compute predicted trajectory + 95% CI for a given issue-2 baseline.
    Uses retention rate model (consistent with train.py forecast_trajectory).
    """
    issues = [2, 6, 12, 24, 36]
    pred   = [issue2_orders]
    ci_lo  = [issue2_orders]
    ci_hi  = [issue2_orders]

    for pt in [6, 12, 24, 36]:
        key = str(pt)
        if key not in retention:
            pred.append(None); ci_lo.append(None); ci_hi.append(None)
            continue
        r    = retention[key]
        mean = r["mean"]
        std  = r["std"]
        n    = r["n"]
        p    = issue2_orders * mean

        if n > 1:
            se    = std / np.sqrt(n)
            t_val = scipy_stats.t.ppf(0.975, df=n - 1)
            lo    = max(0, issue2_orders * (mean - t_val * se))
            hi    = issue2_orders * (mean + t_val * se)
        else:
            lo = p * 0.85
            hi = p * 1.15

        pred.append(p)
        ci_lo.append(lo)
        ci_hi.append(hi)

    return issues, pred, ci_lo, ci_hi


def render():
    page_header(
        kicker="Interactive Tool",
        title="Readership Decay Forecast",
        subtitle="Model a hypothetical ASM relaunch: set your opening baseline, see where the readership lands."
    )

    preds = load_predictions()
    if preds is None:
        st.error("predictions.json not found. Run `python scripts/train.py` to generate it.")
        return

    retention     = preds["retention"]
    vol_trajs     = preds.get("vol_trajectories", [])
    model_meta    = preds["model"]

    # ── Intro ─────────────────────────────────────────────────────────────────
    prose("""
    <p>
    Every Amazing Spider-Man relaunch follows a predictable arc: a spike at launch,
    then decay. The rate of that decay is surprisingly stable across volumes, and
    that stability makes it possible to model.
    </p>
    <p>
    This tool uses <strong>mean retention rates</strong> computed across all five
    ASM relaunch volumes (1999-2022). Enter a hypothetical issue #2 opening and
    the model projects the expected readership at issues #6, #12, #24, and #36,
    along with 95% confidence intervals derived from the historical variance.
    </p>
    """)

    # ── Slider ────────────────────────────────────────────────────────────────
    section_heading("Set Your Opening Baseline")

    col_slider, col_spacer = st.columns([3, 1])
    with col_slider:
        baseline_k = st.slider(
            "Issue #2 opening orders (thousands)",
            min_value=50,
            max_value=250,
            value=120,
            step=5,
            key="forecast_baseline",
            help="Use issue #2 (not #1): the first standard-cover issue, free of variant inflation."
        )

    baseline = baseline_k * 1000
    issues, pred, ci_lo, ci_hi = compute_trajectory(baseline, retention)

    # ── Summary stat cards ────────────────────────────────────────────────────
    st.markdown("<div style='height:0.5rem'></div>", unsafe_allow_html=True)
    card_html = '<div style="display:flex;gap:1rem;flex-wrap:wrap;margin:0.5rem 0 1.5rem;">'
    labels = ["Issue #2", "Issue #6", "Issue #12", "Issue #24", "Issue #36"]
    retentions = [None, 0.726, 0.575, 0.515, 0.403]
    for i, (lbl, p, lo, hi) in enumerate(zip(labels, pred, ci_lo, ci_hi)):
        if p is None:
            continue
        ret_key = str(ISSUE_POINTS[i])
        ret_pct = f"{retention[ret_key]['mean']*100:.0f}% of #2" if ret_key in retention else "n/a"
        p_k  = f"{p/1000:.1f}k"
        lo_k = f"{lo/1000:.1f}k"
        hi_k = f"{hi/1000:.1f}k"
        card_html += (
            f'<div style="background:#111;border:1px solid #222;padding:0.8rem 1.1rem;'
            f'min-width:130px;flex:1;">'
            f'<div style="font-size:0.65rem;color:#888;font-family:\'Courier New\',monospace;'
            f'letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.3rem;">{lbl}</div>'
            f'<div style="font-size:1.6rem;font-family:Bangers,cursive;color:#ffffff;'
            f'letter-spacing:0.05em;line-height:1.1;">{p_k}</div>'
            f'<div style="font-size:0.68rem;color:#555;font-family:\'Courier New\',monospace;'
            f'margin-top:0.25rem;">95% CI: {lo_k}–{hi_k}</div>'
        )
        if i > 0:
            card_html += (
                f'<div style="font-size:0.68rem;color:#e8b84b;font-family:\'Courier New\','
                f'monospace;margin-top:0.1rem;">{ret_pct}</div>'
            )
        card_html += '</div>'
    card_html += '</div>'
    st.markdown(card_html, unsafe_allow_html=True)

    # ── Main forecast chart ────────────────────────────────────────────────────
    section_heading("Projected Decay Trajectory")

    # Toggle: show historical overlays?
    show_history = st.checkbox(
        "Overlay historical ASM volume trajectories",
        value=True,
        key="forecast_show_history"
    )

    fig = go.Figure()

    # Historical volume lines
    if show_history and vol_trajs:
        for vt in vol_trajs:
            vol_num = vt["volume"]
            color   = VOL_COLORS.get(vol_num, "#444")
            x_pts, y_pts = [2], [vt["issue2_k"] * 1000]
            for pt in [6, 12, 24, 36]:
                k = f"issue{pt}_k"
                if k in vt:
                    x_pts.append(pt)
                    y_pts.append(vt[k] * 1000)
            dash_style = "dot" if vol_num == 2 else "dash"
            label = f"Vol.{vol_num} ({vt['year']}) {vt['writer']}"
            fig.add_trace(go.Scatter(
                x=x_pts, y=y_pts,
                mode="lines+markers",
                name=label,
                line=dict(color=color, width=1.5, dash=dash_style),
                marker=dict(size=5),
                opacity=0.65,
                hovertemplate=f"{label}<br>Issue #%{{x}}: %{{y:,.0f}}<extra></extra>",
            ))

    # CI band
    fig.add_trace(go.Scatter(
        x=issues + issues[::-1],
        y=[v if v is not None else 0 for v in ci_hi] +
          [v if v is not None else 0 for v in ci_lo[::-1]],
        fill="toself",
        fillcolor=CI_FILL_COLOR,
        line=dict(color="rgba(0,0,0,0)"),
        showlegend=True,
        name="95% CI",
        hoverinfo="skip",
    ))

    # Predicted scenario line
    fig.add_trace(go.Scatter(
        x=issues,
        y=pred,
        mode="lines+markers",
        name=f"Scenario ({baseline_k}k opener)",
        line=dict(color=SCENARIO_COLOR, width=3),
        marker=dict(size=9, color=SCENARIO_COLOR),
        hovertemplate="Issue #%{x}: <b>%{y:,.0f}</b><extra></extra>",
    ))

    # Annotate floor at issue 12, raised above the line
    if pred[2] is not None:
        fig.add_annotation(
            x=12, y=pred[2],
            text=f"  ~{pred[2]/1000:.0f}k at #12",
            showarrow=False,
            font=dict(color="#e23636", family="Bangers, cursive", size=14),
            xanchor="left",
            yshift=22,
        )

    fig.update_layout(**dict(PLOTLY_LAYOUT))
    fig.update_layout(
        title=dict(text=""),
        height=460,
        margin=dict(t=40, b=50, l=70, r=30),
        xaxis=dict(
            title="Issue Number",
            tickvals=ISSUE_POINTS,
            ticktext=[f"#{p}" for p in ISSUE_POINTS],
            gridcolor="#1a1a1a",
        ),
        yaxis=dict(
            title="Estimated Orders",
            tickformat=",",
            gridcolor="#1a1a1a",
        ),
        legend=dict(
            orientation="v",
            x=1.01, y=1,
            bgcolor="rgba(0,0,0,0)",
            font=dict(size=10),
        ),
        hovermode="x unified",
    )
    st.plotly_chart(fig, use_container_width=True)

    data_note(
        f"Forecast uses mean retention rates across {model_meta['n_samples']} ASM relaunch volumes. "
        f"95% CIs are t-intervals (df = n−1) on the per-volume retention distribution. "
        f"Vol.2 (1999) is included in retention rate calculation but was a structurally different "
        f"market era. Vol.6 (2022) figures are PRH-normalized estimates (±20% error)."
    )

    # ── Retention rate breakdown ───────────────────────────────────────────────
    section_heading("Retention Rate Distribution")

    prose("""
    <p>
    The forecast is anchored on historical retention rates: how much readership survives
    at each issue milestone, expressed as a fraction of the issue #2 baseline.
    These rates are the most robust signal in the data; they are largely independent of
    the opening baseline.
    </p>
    """)

    ret_fig = go.Figure()
    ret_labels = []
    ret_means  = []
    ret_errors = []

    for pt in [6, 12, 24, 36]:
        key = str(pt)
        if key not in retention:
            continue
        r = retention[key]
        ret_labels.append(f"Issue #{pt}")
        ret_means.append(r["mean"] * 100)
        # 95% CI on mean
        if r["n"] > 1:
            se    = r["std"] / np.sqrt(r["n"])
            t_val = scipy_stats.t.ppf(0.975, df=r["n"] - 1)
            ret_errors.append(t_val * se * 100)
        else:
            ret_errors.append(r["std"] * 100 * 1.15)

    ret_fig.add_trace(go.Bar(
        x=ret_labels,
        y=ret_means,
        error_y=dict(type="data", array=ret_errors, visible=True,
                     color="#888", thickness=1.5, width=6),
        marker_color=[SCENARIO_COLOR if m < 55 else "#7799cc" for m in ret_means],
        text=[f"{m:.1f}%" for m in ret_means],
        textposition="outside",
        textfont=dict(family="Bangers, cursive", size=14, color="#ffffff"),
        hovertemplate="%{x}: <b>%{y:.1f}%</b> of #2 baseline<extra></extra>",
    ))

    ret_fig.update_layout(**dict(PLOTLY_LAYOUT))
    ret_fig.update_layout(
        title=dict(text="Historical Retention by Issue Milestone"),
        height=320,
        margin=dict(t=45, b=40, l=60, r=30),
        yaxis=dict(
            title="Retention (% of issue #2)",
            ticksuffix="%",
            range=[0, 110],
            gridcolor="#1a1a1a",
        ),
        xaxis=dict(gridcolor="#1a1a1a"),
        showlegend=False,
    )
    st.plotly_chart(ret_fig, use_container_width=True)

    # ── Interpretation ─────────────────────────────────────────────────────────
    section_heading("What This Means for the Business Case")

    ret12 = retention.get("12", {}).get("mean", 0.575)
    ret24 = retention.get("24", {}).get("mean", 0.515)

    prose(f"""
    <p>
    For a {baseline_k}k opening baseline:
    </p>
    <ul style="color:#d4d4d4;font-family:Georgia,serif;font-size:1.05rem;line-height:1.85;max-width:760px;">
    <li>By issue #12, the run will have shed roughly
        <strong>{(1 - ret12)*100:.0f}% of its launch readership</strong>, down to
        an estimated <strong>{pred[2]/1000:.0f}k copies</strong>.
        This is before any story arc has had time to compound.</li>
    <li>By issue #24, the baseline is
        <strong>{pred[3]/1000:.0f}k</strong>, barely above the floor typically
        needed to justify a title's continuation at major publishers.</li>
    <li>These numbers are a ceiling estimate under current relaunch-cycle conditions.
        They assume the launch has no structural problems (no mid-run creative change,
        no event disruption). In practice, most runs underperform the model.</li>
    <li>A <em>stable, unrelaunched</em> run starting at the same {baseline_k}k
        does not face this decay pressure. The lost issues don't need to rebuild
        an audience from zero every 2–3 years.</li>
    </ul>
    """)

    pull_quote(
        f"At the historical average decay rate, a {baseline_k}k opening becomes "
        f"a {pred[2]/1000:.0f}k run by issue 12. "
        f"That's the cost of the relaunch model, in plain numbers."
    )

    # ── Model transparency ─────────────────────────────────────────────────────
    section_heading("Model Transparency")

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("""
        <div style="background:#0d0d0d;border:1px solid #1e1e1e;padding:1rem 1.25rem;">
        <div style="font-size:0.65rem;color:#e8b84b;font-family:'Courier New',monospace;
        letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.75rem;">What the model is</div>
        <ul style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.88rem;
        line-height:1.75;margin:0;padding-left:1.25rem;">
        <li>Retention rates (mean issue_N/issue_2) across 5 ASM relaunch volumes</li>
        <li>95% confidence intervals via t-distribution on the retention variance</li>
        <li>Trajectories scale linearly from the user baseline</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        st.markdown("""
        <div style="background:#0d0d0d;border:1px solid #1e1e1e;padding:1rem 1.25rem;">
        <div style="font-size:0.65rem;color:#e23636;font-family:'Courier New',monospace;
        letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.75rem;">What the model is not</div>
        <ul style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.88rem;
        line-height:1.75;margin:0;padding-left:1.25rem;">
        <li>Not a causal model (n=5 relaunches, one publisher, one character)</li>
        <li>Not predictive of event-boosted spikes or mid-run creative changes</li>
        <li>Not applicable to launches outside the 2010–2025 direct-market era</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)

    data_note(
        f"Predictions generated {preds['trained_at'][:10]}. "
        f"Retention rates based on n = {model_meta['n_samples']} ASM volumes. "
        f"Update by running scripts/train.py after adding new data to marvel.db."
    )
