"""
src/pages/page8_forecast.py
---------------------------
Readership Decay Forecast: publisher decision tool.

Reads pre-computed retention rates from data/predictions.json (generated by
scripts/train.py) and lets users model launch economics, viability thresholds,
and projected run revenue. No sklearn required at runtime.
"""

import json
import numpy as np
import streamlit as st
import plotly.graph_objects as go
from pathlib import Path
from scipy import stats as scipy_stats

from src.utils.styling import (
    page_header, prose, pull_quote, section_heading, data_note, PLOTLY_LAYOUT
)

PRED_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "predictions.json"

ISSUE_POINTS   = [2, 6, 12, 24, 36]
SCENARIO_COLOR = "#e23636"
CI_FILL_COLOR  = "rgba(226,54,54,0.12)"

# Viability threshold defaults (user-adjustable)
THRESHOLD_DEFAULT = 17_000

# Publisher economics constants
PUBLISHER_MARGIN  = 0.40   # conservative; see citation in render()
COVER_PRICE_DEFAULT = 4.99

VOL_COLORS = {
    2: "#555555",
    3: "#7799cc",
    4: "#77aadd",
    5: "#6fbf7a",
    6: "#e8b84b",
}


@st.cache_data
def load_predictions():
    if not PRED_PATH.exists():
        return None
    with open(PRED_PATH) as f:
        return json.load(f)


def compute_trajectory(issue2_orders, retention):
    """
    Compute predicted trajectory + 95% CI for a given issue-2 baseline.
    Returns (issues, pred, ci_lo, ci_hi) as parallel lists.
    """
    issues = [2, 6, 12, 24, 36]
    pred, ci_lo, ci_hi = [issue2_orders], [issue2_orders], [issue2_orders]

    for pt in [6, 12, 24, 36]:
        key = str(pt)
        if key not in retention:
            pred.append(None); ci_lo.append(None); ci_hi.append(None)
            continue
        r    = retention[key]
        mean, std, n = r["mean"], r["std"], r["n"]
        p = issue2_orders * mean
        if n > 1:
            se    = std / np.sqrt(n)
            t_val = scipy_stats.t.ppf(0.975, df=n - 1)
            lo, hi = max(0, issue2_orders * (mean - t_val * se)), issue2_orders * (mean + t_val * se)
        else:
            lo, hi = p * 0.85, p * 1.15
        pred.append(p); ci_lo.append(lo); ci_hi.append(hi)

    return issues, pred, ci_lo, ci_hi


def compute_run_economics(pred, cover_price, run_length=24):
    """
    Estimate total orders and publisher gross revenue over a run using
    linear interpolation between checkpoint values.

    Arc definitions (non-overlapping, cover issues 2 through run_length):
      Launch:    issues  2-6   (5 issues)
      Early run: issues  7-12  (6 issues)
      Core run:  issues 13-24  (12 issues)  [24-issue total = 23 issues]
      Extended:  issues 25-36  (12 issues)  [36-issue total = 35 issues]
    """
    pub_net = cover_price * PUBLISHER_MARGIN

    # pred index: 0=issue2, 1=issue6, 2=issue12, 3=issue24, 4=issue36
    p2, p6, p12, p24 = pred[0], pred[1], pred[2], pred[3]
    p36 = pred[4] if len(pred) > 4 else None

    arcs = []
    if p2 and p6:
        arcs.append({"label": "Launch (#2-6)",     "n": 5,  "y0": p2,  "y1": p6})
    if p6 and p12:
        arcs.append({"label": "Early Run (#7-12)", "n": 6,  "y0": p6,  "y1": p12})
    if p12 and p24 and run_length >= 24:
        arcs.append({"label": "Core Run (#13-24)", "n": 12, "y0": p12, "y1": p24})
    if p24 and p36 and run_length >= 36:
        arcs.append({"label": "Extended (#25-36)", "n": 12, "y0": p24, "y1": p36})

    for arc in arcs:
        arc["avg_orders"] = (arc["y0"] + arc["y1"]) / 2
        arc["total_orders"] = arc["n"] * arc["avg_orders"]
        arc["revenue"] = arc["total_orders"] * pub_net

    total_issues = sum(a["n"] for a in arcs)
    total_orders = sum(a["total_orders"] for a in arcs)
    total_revenue = sum(a["revenue"] for a in arcs)

    # "Flat" baseline: same issue count at constant issue-2 readership (upper bound)
    flat_orders  = (p2 or 0) * total_issues
    flat_revenue = flat_orders * pub_net
    decay_cost   = flat_revenue - total_revenue

    return {
        "arcs":          arcs,
        "total_issues":  total_issues,
        "total_orders":  total_orders,
        "total_revenue": total_revenue,
        "flat_revenue":  flat_revenue,
        "decay_cost":    decay_cost,
        "pub_net":       pub_net,
    }


def render():
    page_header(
        kicker="Publisher Decision Tool",
        title="Readership Decay Forecast",
        subtitle="Project a relaunch trajectory, assess viability against the cancellation zone, and estimate run economics."
    )

    preds = load_predictions()
    if preds is None:
        st.error("predictions.json not found. Run `python scripts/train.py` to generate it.")
        return

    retention  = preds["retention"]
    vol_trajs  = preds.get("vol_trajectories", [])
    model_meta = preds["model"]

    # ── Intro ──────────────────────────────────────────────────────────────────
    prose("""
    <p>
    Every Amazing Spider-Man relaunch follows a predictable arc: a spike at launch,
    then decay. The rate of that decay is surprisingly stable across volumes, and
    that stability makes it possible to model with enough precision to be useful.
    </p>
    <p>
    This tool uses mean retention rates computed across all five ASM relaunch volumes
    (1999-2022). Set an opening baseline and the model projects readership at issues
    #6, #12, #24, and #36, flags when the trajectory enters the cancellation zone,
    and converts the forecast into projected publisher revenue.
    </p>
    """)

    # ── Slider ─────────────────────────────────────────────────────────────────
    section_heading("Set Your Opening Baseline")

    col_sl, col_sp = st.columns([3, 1])
    with col_sl:
        baseline_k = st.slider(
            "Issue #2 opening orders (thousands)",
            min_value=50, max_value=250, value=120, step=5,
            key="forecast_baseline",
            help="Issue #2 is the first standard-cover issue, free of variant-cover speculation."
        )

    baseline = baseline_k * 1000
    issues, pred, ci_lo, ci_hi = compute_trajectory(baseline, retention)

    # ── Stat cards ─────────────────────────────────────────────────────────────
    st.markdown("<div style='height:0.5rem'></div>", unsafe_allow_html=True)
    card_html = '<div style="display:flex;gap:1rem;flex-wrap:wrap;margin:0.5rem 0 1.5rem;">'
    labels = ["Issue #2", "Issue #6", "Issue #12", "Issue #24", "Issue #36"]
    for i, (lbl, p, lo, hi) in enumerate(zip(labels, pred, ci_lo, ci_hi)):
        if p is None:
            continue
        ret_key = str(ISSUE_POINTS[i])
        ret_pct = f"{retention[ret_key]['mean']*100:.0f}% of #2" if ret_key in retention else "n/a"
        p_k  = f"{p/1000:.1f}k"
        lo_k = f"{lo/1000:.1f}k"
        hi_k = f"{hi/1000:.1f}k"
        card_html += (
            f'<div style="background:#111;border:1px solid #222;padding:0.8rem 1.1rem;'
            f'min-width:130px;flex:1;">'
            f'<div style="font-size:0.65rem;color:#888;font-family:\'Courier New\',monospace;'
            f'letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.3rem;">{lbl}</div>'
            f'<div style="font-size:1.6rem;font-family:Bangers,cursive;color:#ffffff;'
            f'letter-spacing:0.05em;line-height:1.1;">{p_k}</div>'
            f'<div style="font-size:0.68rem;color:#555;font-family:\'Courier New\',monospace;'
            f'margin-top:0.25rem;">95% CI: {lo_k}-{hi_k}</div>'
        )
        if i > 0:
            card_html += (
                f'<div style="font-size:0.68rem;color:#e8b84b;font-family:\'Courier New\','
                f'monospace;margin-top:0.1rem;">{ret_pct}</div>'
            )
        card_html += '</div>'
    card_html += '</div>'
    st.markdown(card_html, unsafe_allow_html=True)

    # ── Trajectory chart ───────────────────────────────────────────────────────
    section_heading("Projected Decay Trajectory")

    col_chk, col_thresh = st.columns([2, 1])
    with col_chk:
        show_history = st.checkbox(
            "Overlay historical ASM volume trajectories",
            value=True, key="forecast_show_history"
        )
    with col_thresh:
        threshold_k = st.number_input(
            "Viability threshold (orders)",
            min_value=5_000, max_value=50_000,
            value=THRESHOLD_DEFAULT, step=1_000,
            key="forecast_threshold",
            help="Adjust based on title and publisher. Default is ~17,000, the historical cancellation range floor."
        )

    fig = go.Figure()

    # Cancellation zone: shaded band from threshold*0.85 to threshold*1.20
    zone_lo = threshold_k * 0.85
    zone_hi = threshold_k * 1.20
    fig.add_shape(
        type="rect",
        x0=2, x1=36,
        y0=zone_lo, y1=zone_hi,
        fillcolor="rgba(232,184,75,0.07)",
        line=dict(color="rgba(0,0,0,0)"),
        layer="below",
    )
    fig.add_hline(
        y=threshold_k,
        line=dict(color="#e8b84b", width=1.5, dash="dot"),
        annotation_text=f"Cancellation zone ({threshold_k/1000:.0f}k)",
        annotation_position="right",
        annotation_font=dict(color="#e8b84b", size=11,
                             family="'Courier New', monospace"),
    )

    # Historical volume lines
    if show_history and vol_trajs:
        for vt in vol_trajs:
            vol_num = vt["volume"]
            color   = VOL_COLORS.get(vol_num, "#444")
            x_pts, y_pts = [2], [vt["issue2_k"] * 1000]
            for pt in [6, 12, 24, 36]:
                k = f"issue{pt}_k"
                if k in vt:
                    x_pts.append(pt)
                    y_pts.append(vt[k] * 1000)
            dash_style = "dot" if vol_num == 2 else "dash"
            label = f"Vol.{vol_num} ({vt['year']}) {vt['writer']}"
            fig.add_trace(go.Scatter(
                x=x_pts, y=y_pts, mode="lines+markers", name=label,
                line=dict(color=color, width=1.5, dash=dash_style),
                marker=dict(size=5), opacity=0.65,
                hovertemplate=f"{label}<br>Issue #%{{x}}: %{{y:,.0f}}<extra></extra>",
            ))

    # CI band
    fig.add_trace(go.Scatter(
        x=issues + issues[::-1],
        y=[v if v is not None else 0 for v in ci_hi] +
          [v if v is not None else 0 for v in ci_lo[::-1]],
        fill="toself", fillcolor=CI_FILL_COLOR,
        line=dict(color="rgba(0,0,0,0)"),
        showlegend=True, name="95% CI", hoverinfo="skip",
    ))

    # Scenario line
    fig.add_trace(go.Scatter(
        x=issues, y=pred, mode="lines+markers",
        name=f"Scenario ({baseline_k}k opener)",
        line=dict(color=SCENARIO_COLOR, width=3),
        marker=dict(size=9, color=SCENARIO_COLOR),
        hovertemplate="Issue #%{x}: <b>%{y:,.0f}</b><extra></extra>",
    ))

    if pred[2] is not None:
        fig.add_annotation(
            x=12, y=pred[2],
            text=f"  ~{pred[2]/1000:.0f}k at #12",
            showarrow=False,
            font=dict(color="#e23636", family="Bangers, cursive", size=14),
            xanchor="left", yshift=22,
        )

    fig.update_layout(**dict(PLOTLY_LAYOUT))
    fig.update_layout(
        title=dict(text=""),
        height=480,
        margin=dict(t=40, b=50, l=70, r=140),
        xaxis=dict(
            title="Issue Number",
            tickvals=ISSUE_POINTS,
            ticktext=[f"#{p}" for p in ISSUE_POINTS],
            gridcolor="#1a1a1a",
        ),
        yaxis=dict(
            title="Estimated Orders",
            tickformat=",",
            gridcolor="#1a1a1a",
        ),
        legend=dict(
            orientation="v", x=1.01, y=1,
            bgcolor="rgba(0,0,0,0)", font=dict(size=10),
        ),
        hovermode="x unified",
    )
    st.plotly_chart(fig, use_container_width=True)

    # ── Viability threshold explanation ────────────────────────────────────────

    # Determine whether the scenario crosses into the zone
    zone_crossings = []
    for i, (iss, p) in enumerate(zip(issues, pred)):
        if p is not None and p < threshold_k * 1.20:
            zone_crossings.append((iss, p))

    first_cross = zone_crossings[0] if zone_crossings else None
    cross_msg = (
        f"At this opening baseline, the trajectory enters the cancellation zone around "
        f"<strong>issue #{first_cross[0]}</strong> "
        f"({first_cross[1]/1000:.0f}k projected orders)."
        if first_cross and first_cross[0] > 2
        else f"At this opening baseline, the trajectory stays above the cancellation zone through issue #36."
        if not first_cross
        else "This opening baseline begins within or near the cancellation zone."
    )

    st.markdown(f"""
    <div style="background:#0d0d0d;border-left:3px solid #e8b84b;
    padding:1rem 1.25rem;margin:0.5rem 0 1.5rem;max-width:820px;">
    <div style="font-size:0.65rem;color:#e8b84b;font-family:'Courier New',monospace;
    letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.6rem;">
    About the Cancellation Zone</div>
    <p style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.9rem;
    line-height:1.7;margin:0 0 0.5rem;">
    The dashed line marks the viability threshold you set above. The shaded band represents
    the uncertainty range around it (&plusmn;15-20%). {cross_msg}
    </p>
    <p style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.9rem;
    line-height:1.7;margin:0 0 0.5rem;">
    Marvel and DC have not published formal cancellation thresholds. The default of
    <strong>17,000 monthly orders</strong> is derived empirically: analysis of Comichron's
    publicly available order charts (comichron.com) shows that the large majority of ongoing
    series cancelled by Marvel between 2015 and 2023 were tracking below 17,000-20,000
    units in the months before cancellation. This figure is consistent with industry
    reporting by ICv2 (icv2.com) and retailer analysis in Brian Hibbs'
    <em>Tilting at Windmills</em> column (The Beat, comicsbeat.com).
    </p>
    <p style="color:#777;font-family:'Courier New',monospace;font-size:0.72rem;
    margin:0;">
    Threshold is adjustable above because it varies by title economics, publisher,
    and era. A flagship title may survive below 17k; a debut series may be cancelled
    above it. Use the number that fits your scenario.
    </p>
    </div>
    """, unsafe_allow_html=True)

    data_note(
        f"Forecast uses mean retention rates across {model_meta['n_samples']} ASM relaunch volumes. "
        f"95% CIs are t-intervals (df = n-1) on the per-volume retention distribution. "
        f"Vol.2 (1999) included in retention calculation but represents a structurally different "
        f"market era. Vol.6 (2022) figures are PRH-normalized estimates (+/-20% error)."
    )

    # ── Run economics ──────────────────────────────────────────────────────────
    section_heading("Projected Run Economics")

    prose("""
    <p>
    Orders are the unit comics people track internally, but dollars are what go into
    a business case. This section converts the decay trajectory into a projected publisher
    gross revenue estimate using standard direct-market economics.
    </p>
    """)

    col_price, col_run = st.columns([1, 1])
    with col_price:
        cover_price = st.slider(
            "Cover price ($)",
            min_value=3.99, max_value=5.99, value=COVER_PRICE_DEFAULT,
            step=0.25, format="$%.2f", key="forecast_cover_price",
            help="Standard Marvel main title cover price. Most ongoing series are $4.99 as of 2024."
        )
    with col_run:
        run_length = st.radio(
            "Run length to model",
            options=[24, 36],
            format_func=lambda x: f"{x} issues (~{x//12} years)",
            horizontal=True,
            key="forecast_run_length",
        )

    econ = compute_run_economics(pred, cover_price, run_length)
    pub_net = econ["pub_net"]

    # Revenue stat cards
    total_rev_m = econ["total_revenue"] / 1_000_000
    decay_cost_m = econ["decay_cost"] / 1_000_000
    avg_monthly = econ["total_revenue"] / econ["total_issues"] / 1_000 if econ["total_issues"] else 0

    econ_card_html = '<div style="display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0 1.5rem;">'

    econ_cards = [
        (f"${total_rev_m:.2f}M",    "Projected publisher gross",         f"Over {econ['total_issues']}-issue run"),
        (f"${avg_monthly:.0f}k/mo", "Avg. monthly publisher gross",      f"At ${pub_net:.2f}/copy net"),
        (f"-${decay_cost_m:.2f}M",  "Revenue lost to decay",             f"vs. flat {baseline_k}k readership"),
    ]
    card_colors = ["#6fbf7a", "#7799cc", "#e23636"]
    for (val, label, sub), col in zip(econ_cards, card_colors):
        econ_card_html += (
            f'<div style="background:#111;border:1px solid #1e1e1e;'
            f'border-top:2px solid {col};padding:0.9rem 1.1rem;min-width:160px;flex:1;">'
            f'<div style="font-size:0.65rem;color:#888;font-family:\'Courier New\',monospace;'
            f'letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.3rem;">{label}</div>'
            f'<div style="font-size:1.6rem;font-family:Bangers,cursive;color:{col};'
            f'letter-spacing:0.05em;line-height:1.1;">{val}</div>'
            f'<div style="font-size:0.68rem;color:#555;font-family:\'Courier New\',monospace;'
            f'margin-top:0.2rem;">{sub}</div>'
            f'</div>'
        )
    econ_card_html += '</div>'
    st.markdown(econ_card_html, unsafe_allow_html=True)

    # Revenue breakdown bar chart
    arc_labels  = [a["label"] for a in econ["arcs"]]
    arc_revs_k  = [a["revenue"] / 1_000 for a in econ["arcs"]]
    arc_orders_k = [a["avg_orders"] / 1_000 for a in econ["arcs"]]

    rev_fig = go.Figure()
    rev_fig.add_trace(go.Bar(
        x=arc_labels,
        y=arc_revs_k,
        marker_color=[SCENARIO_COLOR, "#c04040", "#903030", "#702020"][:len(arc_labels)],
        text=[f"${v:.0f}k" for v in arc_revs_k],
        textposition="outside",
        textfont=dict(family="Bangers, cursive", size=13, color="#ffffff"),
        customdata=[[f"{o:.1f}k", f"{n}"] for o, n in
                    zip(arc_orders_k, [a["n"] for a in econ["arcs"]])],
        hovertemplate=(
            "%{x}<br>"
            "Avg orders: <b>%{customdata[0]}</b>/issue<br>"
            "Issues in arc: <b>%{customdata[1]}</b><br>"
            "Publisher gross: <b>$%{y:.0f}k</b>"
            "<extra></extra>"
        ),
    ))

    rev_fig.update_layout(**dict(PLOTLY_LAYOUT))
    rev_fig.update_layout(
        title=dict(text=f"Publisher Gross Revenue by Arc  (${cover_price:.2f} cover, {PUBLISHER_MARGIN*100:.0f}% net)"),
        height=320,
        margin=dict(t=50, b=40, l=70, r=30),
        yaxis=dict(
            title="Publisher Gross ($k)",
            tickprefix="$",
            ticksuffix="k",
            gridcolor="#1a1a1a",
        ),
        xaxis=dict(gridcolor="#1a1a1a"),
        showlegend=False,
    )
    st.plotly_chart(rev_fig, use_container_width=True)

    # Assumptions callout
    st.markdown(f"""
    <div style="background:#0d0d0d;border-left:3px solid #7799cc;
    padding:1rem 1.25rem;margin:0.5rem 0 1.5rem;max-width:820px;">
    <div style="font-size:0.65rem;color:#7799cc;font-family:'Courier New',monospace;
    letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.6rem;">
    Methodology and Sources</div>
    <p style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.88rem;
    line-height:1.75;margin:0 0 0.6rem;">
    <strong>Publisher net of {PUBLISHER_MARGIN*100:.0f}% of cover price</strong> is a
    conservative estimate based on standard North American direct-market economics.
    Retailers typically purchase at 40-55% off cover price from distributors.
    Diamond Comic Distributors (the dominant distributor through 2021) structured
    publisher payouts at approximately 40% of cover after retailer discounts and
    distribution fees. Penguin Random House, which became Marvel's primary distributor
    in October 2021, has negotiated terms closer to 50% in some cases.
    This model uses 40% as a floor; actual publisher net may be higher.
    Sources: ICv2 (icv2.com), Comichron (comichron.com),
    and retailer analysis in <em>Tilting at Windmills</em> (The Beat, comicsbeat.com).
    </p>
    <p style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.88rem;
    line-height:1.75;margin:0 0 0.6rem;">
    <strong>Revenue projections represent publisher gross, not profit.</strong>
    Production costs (writer, penciler, inker, colorist, letterer, editorial) for a
    flagship Marvel title are not publicly disclosed but are estimated in industry
    reporting at $15,000-$30,000 per issue for a full creative team.
    Net margin after production is substantially lower than gross.
    </p>
    <p style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.88rem;
    line-height:1.75;margin:0;">
    <strong>Order estimates use trapezoidal interpolation</strong> between the model's
    checkpoints at issues #2, #6, #12, #24, and #36. Each arc assumes linear decay
    between endpoints. Total issues: {econ['total_issues']} (issues 2 through {run_length}).
    </p>
    </div>
    """, unsafe_allow_html=True)

    pull_quote(
        f"At the historical decay rate, a {baseline_k}k opening generates "
        f"${total_rev_m:.1f}M in publisher gross over {run_length} issues. "
        f"Decay costs ${decay_cost_m:.1f}M vs. a stable readership. "
        f"That is the dollar value of the relaunch problem."
    )

    # ── Relaunch vs. Continue ──────────────────────────────────────────────────
    section_heading("Relaunch vs. Continue: The Decision")

    prose("""
    <p>
    The scenarios above model the relaunch in isolation. The actual editorial decision
    is a comparison: does relaunching generate more readership and revenue than continuing
    the existing run? Set the current title's readership below and the model runs both
    trajectories side by side, identifies the break-even point if one exists, and
    computes the revenue delta over your chosen horizon.
    </p>
    <p>
    The relaunch carries a two-issue startup cost: months 0 and 1 generate zero direct
    orders while the new volume is in production. The comparison reflects that.
    </p>
    """)

    col_cur, col_dc = st.columns([1, 1])
    with col_cur:
        current_k = st.number_input(
            "Current run readership (orders/month)",
            min_value=5_000, max_value=300_000, value=60_000, step=5_000,
            key="rvc_current",
            help="The existing title's sustained monthly orders before any relaunch decision."
        )
    with col_dc:
        annual_decline_pct = st.slider(
            "Organic annual decline without relaunch (%/yr)",
            min_value=0, max_value=25, value=8, step=1,
            key="rvc_decline",
            help=(
                "Expected yearly readership decay if the run continues unchanged. "
                "Derived from the ASM retention data: mid-run (issues 12-24) sees "
                "roughly 8-10% annual decay. 8% is a conservative default."
            )
        )

    # ── Continuation trajectory ────────────────────────────────────────────────
    # Monthly decline rate (each issue = one month for a standard ongoing)
    issue_decline = (1 - annual_decline_pct / 100) ** (1 / 12)
    x_range   = list(range(0, run_length + 1))
    cont_y    = [current_k * (issue_decline ** i) for i in x_range]

    # ── Relaunch trajectory (aligned to same x axis) ───────────────────────────
    # x=0 = decision point, x=2 = new vol. issue #2, x=6 = issue #6, etc.
    relaunch_x = issues          # [2, 6, 12, 24, 36] — absolute issue numbers == months from decision
    relaunch_y = pred            # predicted orders at each checkpoint

    # Linear interpolation helper for relaunch at any integer x
    def interp_relaunch(x):
        valid = [(xi, yi) for xi, yi in zip(relaunch_x, relaunch_y) if yi is not None]
        if not valid or x < valid[0][0]:
            return 0.0
        for i in range(len(valid) - 1):
            x0, y0 = valid[i]
            x1, y1 = valid[i + 1]
            if x0 <= x <= x1:
                return y0 + (y1 - y0) * (x - x0) / (x1 - x0)
        return float(valid[-1][1])

    # ── Break-even: first issue where relaunch readership > continuation ────────
    readership_be = None
    for x in range(2, run_length + 1):
        if interp_relaunch(x) > cont_y[x]:
            readership_be = x
            break

    # ── Revenue over the comparison window ─────────────────────────────────────
    # Relaunch: zero revenue at months 0-1; revenue from month 2 onward
    relaunch_rev = sum(interp_relaunch(x) * pub_net for x in range(2, run_length + 1))
    # Continuation: revenue from month 0 onward
    cont_rev = sum(cont_y[x] * pub_net for x in range(0, run_length + 1))
    rev_delta = relaunch_rev - cont_rev

    # ── Cumulative revenue series (both scenarios) ─────────────────────────────
    cum_relaunch = []
    cum_cont     = []
    running_r = running_c = 0.0
    revenue_be = None
    for x in x_range:
        running_r += interp_relaunch(x) * pub_net / 1_000
        running_c += cont_y[x] * pub_net / 1_000
        cum_relaunch.append(running_r)
        cum_cont.append(running_c)
        if revenue_be is None and running_r > running_c and x >= 2:
            revenue_be = x

    # ── Trajectory comparison chart ────────────────────────────────────────────
    rvc_fig = go.Figure()

    # Cancellation zone
    rvc_fig.add_shape(
        type="rect", x0=0, x1=run_length,
        y0=threshold_k * 0.85, y1=threshold_k * 1.20,
        fillcolor="rgba(232,184,75,0.07)",
        line=dict(color="rgba(0,0,0,0)"), layer="below",
    )
    rvc_fig.add_hline(
        y=threshold_k,
        line=dict(color="#e8b84b", width=1.5, dash="dot"),
        annotation_text=f"Cancellation zone ({threshold_k/1000:.0f}k)",
        annotation_position="right",
        annotation_font=dict(color="#e8b84b", size=10,
                             family="'Courier New', monospace"),
    )

    # Continuation
    rvc_fig.add_trace(go.Scatter(
        x=x_range, y=cont_y,
        mode="lines", name=f"Continue ({current_k//1000}k, -{annual_decline_pct}%/yr)",
        line=dict(color="#7799cc", width=2.5, dash="dash"),
        hovertemplate="Month +%{x}: <b>%{y:,.0f}</b> (continue)<extra></extra>",
    ))

    # Relaunch CI band (only from issue 2 onward)
    ci_x_fwd  = [x for x in issues if x <= run_length]
    ci_hi_fwd = [v for x, v in zip(issues, ci_hi) if x <= run_length]
    ci_lo_fwd = [v for x, v in zip(issues, ci_lo) if x <= run_length]
    rvc_fig.add_trace(go.Scatter(
        x=ci_x_fwd + ci_x_fwd[::-1],
        y=[v if v else 0 for v in ci_hi_fwd] +
          [v if v else 0 for v in ci_lo_fwd[::-1]],
        fill="toself", fillcolor=CI_FILL_COLOR,
        line=dict(color="rgba(0,0,0,0)"),
        showlegend=True, name="Relaunch 95% CI", hoverinfo="skip",
    ))

    # Relaunch line
    rl_x_plot = [x for x in issues if x <= run_length]
    rl_y_plot = [p for x, p in zip(issues, pred) if x <= run_length and p is not None]
    rvc_fig.add_trace(go.Scatter(
        x=rl_x_plot, y=rl_y_plot,
        mode="lines+markers", name=f"Relaunch ({baseline_k}k opener)",
        line=dict(color=SCENARIO_COLOR, width=3),
        marker=dict(size=8, color=SCENARIO_COLOR),
        hovertemplate="Month +%{x}: <b>%{y:,.0f}</b> (relaunch)<extra></extra>",
    ))

    # Break-even vertical line
    if readership_be is not None:
        rvc_fig.add_vline(
            x=readership_be,
            line=dict(color="#6fbf7a", width=1.5, dash="dot"),
            annotation_text=f"Relaunch ahead: month #{readership_be}",
            annotation_position="top right",
            annotation_font=dict(color="#6fbf7a", size=12, family="Bangers, cursive"),
        )
    else:
        rvc_fig.add_annotation(
            x=(run_length * 0.55), y=float(baseline) * 0.92,
            text="Relaunch never exceeds continuation",
            showarrow=False,
            font=dict(color="#e8b84b", size=13, family="Bangers, cursive"),
        )

    rvc_fig.update_layout(**dict(PLOTLY_LAYOUT))
    rvc_fig.update_layout(
        title=dict(text=""),
        height=460,
        margin=dict(t=30, b=50, l=70, r=160),
        xaxis=dict(
            title=f"Months from Decision (0 = now, relaunch ships at month 2)",
            gridcolor="#1a1a1a",
            range=[-0.5, run_length + 0.5],
        ),
        yaxis=dict(
            title="Estimated Orders",
            tickformat=",", gridcolor="#1a1a1a",
        ),
        legend=dict(orientation="v", x=1.01, y=1,
                    bgcolor="rgba(0,0,0,0)", font=dict(size=10)),
        hovermode="x unified",
    )
    st.plotly_chart(rvc_fig, use_container_width=True)

    # ── Revenue comparison stat cards ──────────────────────────────────────────
    winner_label = "Relaunch wins" if rev_delta > 0 else "Continue wins"
    winner_color = SCENARIO_COLOR if rev_delta > 0 else "#7799cc"
    be_label = f"Month #{readership_be}" if readership_be else f"Never (in {run_length})"
    be_color = "#6fbf7a" if readership_be else "#888"

    rvc_card_html = '<div style="display:flex;gap:1rem;flex-wrap:wrap;margin:0.75rem 0 1.25rem;">'
    rvc_cards = [
        (f"${relaunch_rev/1_000_000:.2f}M", "Relaunch gross",
         f"Months 2-{run_length}", SCENARIO_COLOR),
        (f"${cont_rev/1_000_000:.2f}M",     "Continue gross",
         f"Months 0-{run_length}", "#7799cc"),
        (f"${abs(rev_delta)/1_000_000:.2f}M", winner_label,
         f"revenue delta over {run_length} months", winner_color),
        (be_label, "Readership break-even",
         "when relaunch per-issue orders exceed continuation", be_color),
    ]
    for val, label, sub, col in rvc_cards:
        rvc_card_html += (
            f'<div style="background:#111;border:1px solid #1e1e1e;'
            f'border-top:2px solid {col};padding:0.9rem 1.1rem;min-width:160px;flex:1;">'
            f'<div style="font-size:0.65rem;color:#888;font-family:\'Courier New\',monospace;'
            f'letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.3rem;">{label}</div>'
            f'<div style="font-size:1.5rem;font-family:Bangers,cursive;color:{col};'
            f'letter-spacing:0.05em;line-height:1.1;">{val}</div>'
            f'<div style="font-size:0.68rem;color:#555;font-family:\'Courier New\',monospace;'
            f'margin-top:0.2rem;">{sub}</div>'
            f'</div>'
        )
    rvc_card_html += '</div>'
    st.markdown(rvc_card_html, unsafe_allow_html=True)

    # ── Cumulative revenue chart ───────────────────────────────────────────────
    cum_fig = go.Figure()
    cum_fig.add_trace(go.Scatter(
        x=x_range, y=cum_cont,
        name="Continue", mode="lines",
        line=dict(color="#7799cc", width=2.5),
        fill="tozeroy", fillcolor="rgba(119,153,204,0.06)",
        hovertemplate="Month +%{x}: $%{y:.0f}k cumulative<extra></extra>",
    ))
    cum_fig.add_trace(go.Scatter(
        x=x_range, y=cum_relaunch,
        name="Relaunch", mode="lines",
        line=dict(color=SCENARIO_COLOR, width=2.5),
        fill="tozeroy", fillcolor="rgba(226,54,54,0.06)",
        hovertemplate="Month +%{x}: $%{y:.0f}k cumulative<extra></extra>",
    ))

    if revenue_be is not None:
        cum_fig.add_vline(
            x=revenue_be,
            line=dict(color="#6fbf7a", width=1.5, dash="dot"),
            annotation_text=f"Revenue crossover: month #{revenue_be}",
            annotation_position="top left" if revenue_be > run_length * 0.6 else "top right",
            annotation_font=dict(color="#6fbf7a", size=12, family="Bangers, cursive"),
        )

    cum_fig.update_layout(**dict(PLOTLY_LAYOUT))
    cum_fig.update_layout(
        title=dict(text="Cumulative Publisher Gross: Relaunch vs. Continue"),
        height=320,
        margin=dict(t=50, b=40, l=80, r=30),
        xaxis=dict(title="Months from Decision", gridcolor="#1a1a1a"),
        yaxis=dict(
            title="Cumulative Gross ($k)",
            tickprefix="$", ticksuffix="k", gridcolor="#1a1a1a",
        ),
        legend=dict(orientation="h", x=0, y=1.12,
                    bgcolor="rgba(0,0,0,0)", font=dict(size=11)),
        hovermode="x unified",
    )
    st.plotly_chart(cum_fig, use_container_width=True)

    # ── Verdict box ────────────────────────────────────────────────────────────
    if readership_be is None and rev_delta <= 0:
        verdict_color = "#7799cc"
        verdict_icon  = "CONTINUE"
        verdict_text  = (
            f"At a <strong>{baseline_k}k relaunch baseline</strong> and "
            f"<strong>{current_k//1000}k current readership</strong> with "
            f"<strong>{annual_decline_pct}% annual organic decay</strong>, "
            f"the relaunch never achieves higher per-issue readership than simply "
            f"continuing the run, and generates "
            f"<strong>${abs(rev_delta)/1_000_000:.2f}M less</strong> over "
            f"{run_length} months. The spike does not compensate for the startup gap "
            f"or the depth of the current readership advantage."
        )
    elif readership_be is not None and rev_delta > 0:
        verdict_color = SCENARIO_COLOR
        verdict_icon  = "RELAUNCH"
        verdict_text  = (
            f"At a <strong>{baseline_k}k relaunch baseline</strong> and "
            f"<strong>{current_k//1000}k current readership</strong> with "
            f"<strong>{annual_decline_pct}% annual organic decay</strong>, "
            f"the relaunch overtakes the continuation run in per-issue readership "
            f"at <strong>month #{readership_be}</strong> and generates "
            f"<strong>${abs(rev_delta)/1_000_000:.2f}M more</strong> over "
            f"{run_length} months."
        )
    else:
        verdict_color = "#e8b84b"
        verdict_icon  = "MIXED"
        verdict_text  = (
            f"At a <strong>{baseline_k}k relaunch baseline</strong> and "
            f"<strong>{current_k//1000}k current readership</strong> with "
            f"<strong>{annual_decline_pct}% annual organic decay</strong>, "
            f"the relaunch "
            + (f"overtakes continuation readership at month #{readership_be} "
               if readership_be else "never matches per-issue continuation readership ")
            + f"but generates "
            f"<strong>${abs(rev_delta)/1_000_000:.2f}M "
            f"{'more' if rev_delta > 0 else 'less'}</strong> in total over {run_length} months. "
            f"Adjust the inputs to find the threshold that changes the outcome."
        )

    st.markdown(f"""
    <div style="background:#0d0d0d;border:2px solid {verdict_color};
    padding:1.25rem 1.5rem;margin:0.75rem 0 1.5rem;max-width:820px;">
    <div style="font-size:0.65rem;color:{verdict_color};font-family:'Courier New',monospace;
    letter-spacing:0.15em;text-transform:uppercase;margin-bottom:0.6rem;">
    Verdict: {verdict_icon}</div>
    <p style="color:#d4d4d4;font-family:Georgia,serif;font-size:1rem;
    line-height:1.75;margin:0;">{verdict_text}</p>
    </div>
    """, unsafe_allow_html=True)

    data_note(
        f"Continuation trajectory: {annual_decline_pct}% annual organic decay "
        f"(~{(1 - issue_decline) * 100:.1f}%/issue), compounded monthly from {current_k//1000}k baseline. "
        f"Relaunch trajectory: historical ASM retention rates from {baseline_k}k. "
        f"Relaunch carries a two-month startup cost (zero orders at months 0-1). "
        f"Revenue uses ${pub_net:.2f}/copy publisher net "
        f"({PUBLISHER_MARGIN*100:.0f}% of ${cover_price:.2f} cover). "
        f"Organic decline default (8%/yr) derived from ASM mid-run retention data "
        f"(issues 12-24 show ~8-10% annual readership loss). "
        f"Neither scenario includes trade paperback, digital, or international revenue."
    )

    # ── Opportunity cost: the tipping point ───────────────────────────────────
    section_heading("The Opportunity Cost: Point of No Return")

    prose("""
    <p>
    The comparison above answers "should we relaunch this specific title right now?"
    But that question misses the deeper one: <strong>how did we get here?</strong>
    </p>
    <p>
    Every relaunch resets the decay clock. The title spikes, then decays again.
    The next time the question comes up, the current readership is lower than it would
    have been under a stable run, and the relaunch opening is unlikely to be higher.
    The tipping point moves closer with each cycle. Eventually the math forces
    a relaunch not because it is the best creative decision, but because continuation
    has become financially untenable.
    </p>
    <p>
    The calculation below shows the exact readership floor at which relaunching
    becomes the financially rational choice, given your current assumptions.
    It is not a recommendation to relaunch. It is a diagnostic:
    if your title is below this number, the relaunch model has already done its damage.
    </p>
    """)

    # ── Tipping point calculation ──────────────────────────────────────────────
    # The financial tipping point C* is where continuation revenue = relaunch revenue.
    # continuation_rev(C*) = pub_net * C* * sum(d^i for i=0..run_length)
    # relaunch_rev           = (fixed, computed above)
    # => C* = relaunch_rev / (pub_net * sum(d^i))
    sum_d = sum(issue_decline ** i for i in range(run_length + 1))
    tipping_point = relaunch_rev / (pub_net * sum_d) if sum_d > 0 else 0

    gap          = current_k - tipping_point
    gap_k        = gap / 1_000
    pct_above    = gap / tipping_point * 100 if tipping_point > 0 else 0
    is_safe      = current_k >= tipping_point
    status_color = "#6fbf7a" if is_safe else SCENARIO_COLOR
    status_label = "ABOVE TIPPING POINT" if is_safe else "BELOW TIPPING POINT"
    status_msg   = (
        f"{abs(gap_k):.0f}k above — continuing is the financially rational choice"
        if is_safe else
        f"{abs(gap_k):.0f}k below — the numbers favor a relaunch at this baseline"
    )

    # ── Tipping point display ──────────────────────────────────────────────────
    col_tp, col_status = st.columns([1, 1])
    with col_tp:
        st.markdown(f"""
        <div style="background:#0d0d0d;border:1px solid #222;
        padding:1.2rem 1.4rem;height:100%;">
        <div style="font-size:0.65rem;color:#888;font-family:'Courier New',monospace;
        letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.4rem;">
        Financial tipping point</div>
        <div style="font-size:2.6rem;font-family:Bangers,cursive;color:#e8b84b;
        letter-spacing:0.05em;line-height:1.0;">{tipping_point/1000:.0f}k</div>
        <div style="font-size:0.78rem;color:#888;font-family:Georgia,serif;
        margin-top:0.4rem;line-height:1.5;">
        Current readership below which a {baseline_k}k relaunch generates more
        publisher gross than continuing over {run_length} months
        at {annual_decline_pct}% annual decay.
        </div>
        </div>
        """, unsafe_allow_html=True)
    with col_status:
        st.markdown(f"""
        <div style="background:#0d0d0d;border:2px solid {status_color};
        padding:1.2rem 1.4rem;height:100%;">
        <div style="font-size:0.65rem;color:{status_color};font-family:'Courier New',monospace;
        letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.4rem;">
        {status_label}</div>
        <div style="font-size:2.6rem;font-family:Bangers,cursive;color:{status_color};
        letter-spacing:0.05em;line-height:1.0;">{current_k//1000}k</div>
        <div style="font-size:0.78rem;color:#888;font-family:Georgia,serif;
        margin-top:0.4rem;line-height:1.5;">
        Your current readership. {status_msg}.
        </div>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<div style='height:1rem'></div>", unsafe_allow_html=True)

    # ── Horizontal comparison bar ──────────────────────────────────────────────
    tp_fig = go.Figure()
    bar_vals   = [tipping_point / 1_000, current_k / 1_000]
    bar_labels = ["Financial tipping point", f"Current readership ({current_k//1000}k)"]
    bar_colors = ["#e8b84b", status_color]
    bar_text   = [f"{tipping_point/1000:.0f}k", f"{current_k//1000}k"]

    tp_fig.add_trace(go.Bar(
        x=bar_vals,
        y=bar_labels,
        orientation="h",
        marker_color=bar_colors,
        text=bar_text,
        textposition="outside",
        textfont=dict(family="Bangers, cursive", size=16, color="#ffffff"),
        hovertemplate="%{y}: <b>%{x:.0f}k orders</b><extra></extra>",
        width=0.45,
    ))

    # Viability threshold marker
    tp_fig.add_vline(
        x=threshold_k / 1_000,
        line=dict(color="#555", width=1.5, dash="dot"),
        annotation_text="Cancellation zone",
        annotation_position="top right",
        annotation_font=dict(color="#555", size=10, family="'Courier New', monospace"),
    )

    tp_fig.update_layout(**dict(PLOTLY_LAYOUT))
    tp_fig.update_layout(
        title=dict(text=""),
        height=200,
        margin=dict(t=20, b=30, l=200, r=100),
        xaxis=dict(
            title="Orders (thousands)",
            ticksuffix="k",
            gridcolor="#1a1a1a",
            range=[0, max(bar_vals) * 1.35],
        ),
        yaxis=dict(gridcolor="#1a1a1a"),
        showlegend=False,
    )
    st.plotly_chart(tp_fig, use_container_width=True)

    # ── The trap narrative ─────────────────────────────────────────────────────
    opp_cost_m = abs(rev_delta) / 1_000_000

    prose(f"""
    <p>
    <strong>The trap is self-reinforcing.</strong> A title launches, decays, and falls
    toward its tipping point. At some point, the relaunch math starts to look compelling.
    A new #1 is ordered. The title spikes, then decays again, this time from a lower
    structural ceiling because the audience has been trained to treat each new volume
    as disposable. The next tipping point arrives sooner. The cycle repeats.
    </p>
    <p>
    Under the current inputs, the opportunity cost of the wrong decision is
    <strong>${opp_cost_m:.2f}M in publisher gross over {run_length} months</strong>:
    that is the revenue difference between the financially optimal path and the
    suboptimal one.
    {'That cost is real even if the relaunch "feels" like progress.'
     if not is_safe else
     'That cost falls on whichever publisher relaunches a title that still has readership worth protecting.'}
    </p>
    <p>
    <strong>How to avoid the trap:</strong> The tipping point is not fixed.
    It rises when the relaunch opening baseline rises (harder to achieve if the brand
    has been devalued by repeated resets) and falls when the organic decay rate falls
    (which happens when creative teams are given long enough to build the reader
    relationship that makes people stay). A title that never relaunches never faces
    this calculation. The tipping point only becomes relevant after the first reset.
    </p>
    """)

    pull_quote(
        f"The tipping point at this scenario is {tipping_point/1000:.0f}k. "
        f"Below that number, relaunching is the rational financial move. "
        f"The relaunch model spends years manufacturing the conditions "
        f"that make that number unavoidable."
    )

    # ── Retention rate distribution ────────────────────────────────────────────
    section_heading("Retention Rate Distribution")

    prose("""
    <p>
    The forecast and revenue model are both anchored on these retention rates: the fraction of
    issue #2 readership that survives to each milestone, averaged across all five ASM relaunch
    volumes. The error bars show 95% confidence intervals; the wide band at issue #24 reflects
    genuine variance in the historical data, not model uncertainty.
    </p>
    """)

    ret_fig = go.Figure()
    ret_labels, ret_means, ret_errors = [], [], []
    for pt in [6, 12, 24, 36]:
        key = str(pt)
        if key not in retention:
            continue
        r = retention[key]
        ret_labels.append(f"Issue #{pt}")
        ret_means.append(r["mean"] * 100)
        if r["n"] > 1:
            se    = r["std"] / np.sqrt(r["n"])
            t_val = scipy_stats.t.ppf(0.975, df=r["n"] - 1)
            ret_errors.append(t_val * se * 100)
        else:
            ret_errors.append(r["std"] * 100 * 1.15)

    ret_fig.add_trace(go.Bar(
        x=ret_labels, y=ret_means,
        error_y=dict(type="data", array=ret_errors, visible=True,
                     color="#888", thickness=1.5, width=6),
        marker_color=[SCENARIO_COLOR if m < 55 else "#7799cc" for m in ret_means],
        text=[f"{m:.1f}%" for m in ret_means],
        textposition="outside",
        textfont=dict(family="Bangers, cursive", size=14, color="#ffffff"),
        hovertemplate="%{x}: <b>%{y:.1f}%</b> of #2 baseline<extra></extra>",
    ))

    ret_fig.update_layout(**dict(PLOTLY_LAYOUT))
    ret_fig.update_layout(
        title=dict(text="Historical Retention by Issue Milestone"),
        height=320,
        margin=dict(t=45, b=40, l=60, r=30),
        yaxis=dict(
            title="Retention (% of issue #2)",
            ticksuffix="%", range=[0, 110],
            gridcolor="#1a1a1a",
        ),
        xaxis=dict(gridcolor="#1a1a1a"),
        showlegend=False,
    )
    st.plotly_chart(ret_fig, use_container_width=True)

    # ── Model transparency ─────────────────────────────────────────────────────
    section_heading("Model Transparency")

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("""
        <div style="background:#0d0d0d;border:1px solid #1e1e1e;padding:1rem 1.25rem;">
        <div style="font-size:0.65rem;color:#e8b84b;font-family:'Courier New',monospace;
        letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.75rem;">What the model is</div>
        <ul style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.88rem;
        line-height:1.75;margin:0;padding-left:1.25rem;">
        <li>Mean retention rates (issue_N/issue_2) across 5 ASM relaunch volumes</li>
        <li>95% CIs via t-distribution on the per-volume retention variance</li>
        <li>Revenue estimated from trapezoidal interpolation x publisher net margin</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        st.markdown("""
        <div style="background:#0d0d0d;border:1px solid #1e1e1e;padding:1rem 1.25rem;">
        <div style="font-size:0.65rem;color:#e23636;font-family:'Courier New',monospace;
        letter-spacing:0.12em;text-transform:uppercase;margin-bottom:0.75rem;">What the model is not</div>
        <ul style="color:#c0c0c0;font-family:Georgia,serif;font-size:0.88rem;
        line-height:1.75;margin:0;padding-left:1.25rem;">
        <li>Not a causal model (n=5 relaunches, one publisher, one character)</li>
        <li>Not predictive of event-boosted spikes or mid-run creative changes</li>
        <li>Does not include trade paperback, digital, or international revenue</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)

    data_note(
        f"Predictions generated {preds['trained_at'][:10]}. "
        f"Retention rates based on n = {model_meta['n_samples']} ASM volumes. "
        f"Refresh by running scripts/train.py after adding new data to marvel.db."
    )
